### ISSUE TITLE
Request for pretrained model

### ISSUE THREAD

**Issue by super233** [alpc91/TransDA#1]
Hi, thanks for your sharing code, it's really a awesome work on UDA.

Would you please share the pretrained model? I'm going to research under your work, the pretrained model will be helpful for me.

Looking forward your reply. :-)

**Comment by BatGrey** [comment]
这是来自QQ邮箱的假期自动回复邮件。嘟嘟噜，龙王开始工作了，本人已收到你的邮件

**Comment by alpc91** [comment]
> Hi, thanks for your sharing code, it's really a awesome work on UDA.
> 
> Would you please share the pretrained model? I'm going to research under your work, the pretrained model will be helpful for me.
> 
> Looking forward your reply. :-)

Uploaded.
